

diferidasSuccess:
 has_layout:     on
 layout:         layout
todosSuccess:
 has_layout:     on
 layout:         layout
showSuccess:
  has_layout:     on
  layout:         layout
busquedaSuccess:
  has_layout:     on
  layout:         layout
calendarSuccess:
  has_layout:     on
  layout:         layout_sn
busquedapersonalisadaSuccess:
  has_layout:     on
  layout:         layout
canceladasSuccess:
  has_layout:     on
  layout:         layout

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  # stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
