<?php



/**
 * Skeleton subclass for representing a row from the 'hc_agenda_personal' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Wed Jul 17 10:47:20 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model.data
 */
class Personalcirugia extends BasePersonalcirugia
{
  public function __toString() {
    return $this->getPersonalNombre();
  }

  /* functionname
  * @autor: Antonio Sánchez Uresti
  * @date:  2014-04-06
  */
  public function getTurno()
  {
    switch (parent::getTurno())
    {
      case 1: return 'Matutino';
      case 2: return 'Vespertino';
      case 3: return 'Nocturno';
      case 4: return 'Plan Piloto';
    }
  }

}
