<?php



/**
 * Skeleton subclass for representing a row from the 'hc_agenda_reporte' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon May 12 20:59:54 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model.data
 */
class Reporteqx extends BaseReporteqx
{
}
